# Generated by Django 5.2.3 on 2025-06-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('laptop_no', models.CharField(max_length=10)),
                ('issued_date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
