# Generated by Django 5.2.3 on 2025-06-18 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_delete_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='issued_date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='laptop_no',
            field=models.CharField(max_length=20),
        ),
    ]
