# Generated by Django 5.2.3 on 2025-06-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_remove_employee_email_remove_employee_emp_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hostname',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='laptop_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='username',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
