# Generated by Django 5.2.3 on 2025-06-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeStationary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('purchase_date', models.DateField()),
                ('warranty_years', models.PositiveIntegerField(help_text='How many years of warranty does this product have?')),
                ('make_in', models.CharField(help_text='Model name or company name', max_length=100)),
            ],
        ),
    ]
