# Generated by Django 5.2.3 on 2025-06-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_stationary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='officestationary',
            name='activation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='officestationary',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='officestationary',
            name='mail_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
